apiVersion: v1
kind: Pod
metadata:
  name: baseline-violations
  namespace: default
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: c
    image: nginx
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
      seccompProfile:
        type: Unconfined
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory

