apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ns-requires-owner
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: require-owner
    match:
      resources:
        kinds: ["Namespace"]
    validate:
      message: "Namespaces must have label owner"
      pattern:
        metadata:
          labels:
            owner: "?*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cpolr-pass
  labels:
    owner: me
---
apiVersion: v1
kind: Namespace
metadata:
  name: cpolr-fail

