# KIND cluster configuration for N4K 1.14 + Reports Server testing
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kyverno-reports-test

# 3-node cluster: 1 control plane + 2 worker nodes
nodes:
- role: control-plane
  image: kindest/node:v1.29.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  # NOTE: etcd hostPath mount disabled to avoid kubelet startup issues in KIND
  #extraMounts:
  #- hostPath: /tmp/etcd-data
  #  containerPath: /var/lib/etcd
    
- role: worker
  image: kindest/node:v1.29.0
  labels:
    tier: compute
    
- role: worker  
  image: kindest/node:v1.29.0
  labels:
    tier: compute

# Networking configuration
networking:
  # Disable default CNI to install Calico for testing
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
 
