apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reports-server-etcd-metrics
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kyverno
  selector:
    matchLabels:
      app: etcd-reports-server
  endpoints:
  - port: etcd-metrics
    path: /metrics
    interval: 30s

